export function buildColabNotebook(code: string, language = "python") {
  const kernel =
    language === "python" || language === "py"
      ? { name: "python3", display_name: "Python 3", language: "python" }
      : { name: language, display_name: language, language };

  return {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      colab: {
        name: "devdocs_ai.ipynb",
        provenance: [],
      },
      kernelspec: kernel,
    },
    cells: [
      {
        cell_type: "markdown",
        metadata: {},
        source: [
          "# Generated by DevDocs AI\n",
          "\n",
          "Run the code cell below. You may need to install dependencies first.\n",
        ],
      },
      {
        cell_type: "code",
        metadata: {},
        source: code.split("\n").map((line, index, lines) =>
          index < lines.length - 1 ? `${line}\n` : line
        ),
        execution_count: null,
        outputs: [],
      },
    ],
  };
}

export function encodeColabPayload(code: string): string {
  const bytes = new TextEncoder().encode(code);
  let binary = "";
  bytes.forEach((b) => {
    binary += String.fromCharCode(b);
  });
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

export function buildColabNotebookUrl(code: string, language: string): string {
  const origin =
    typeof window !== "undefined" ? window.location.origin : "";
  const params = new URLSearchParams({
    code: encodeColabPayload(code),
    lang: language,
  });
  const notebookUrl = `${origin}/api/colab/export.ipynb?${params.toString()}`;
  return `https://colab.research.google.com/#notebookUrl=${encodeURIComponent(notebookUrl)}`;
}

export function openInColab(
  code: string,
  language: string
): { mode: "notebook" | "clipboard" } {
  const colabUrl = buildColabNotebookUrl(code, language);

  if (colabUrl.length > 1900) {
    void navigator.clipboard.writeText(code);
    window.open("https://colab.research.google.com/#create=true", "_blank");
    return { mode: "clipboard" };
  }

  window.open(colabUrl, "_blank");
  return { mode: "notebook" };
}